import LogoBrand from './logo.png'
import LogoKontak from './logo-kontak.png'
import TittleIm from './title.png'
import FotoPribadi from './akmal.png'
import Iconaja from './icon.png'
import LogoKampus from './stmik.png'
import JamAbout from './jam.png'
import Poster1 from './poster1.png'
import Poster2 from './poster2.png'
export {LogoBrand, LogoKontak, TittleIm, FotoPribadi, Iconaja, LogoKampus,JamAbout, Poster1,Poster2}